---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- argocd.namespace.yaml
- argocd.install.yaml
patches:
- path: argocd.config.yaml
  target:
    kind: ConfigMap
    name: argocd-cm
