apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  exec.enabled: "false"
  statusbadge.enabled: "false"
  timeout.hard.reconciliation: "0s"
  timeout.reconciliation: "180s"
