apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - https://github.com/argoproj/argo-cd//manifests/cluster-install?ref=v3.3.0
  - cmp-plugin.yaml

patches:
  - path: argocd-repo-server.yaml
  - path: config.yaml
  - path: argocd-cmd-params.yaml
