---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - restic-credentials.yaml
  # Add ReplicationSource resources for each PVC you want to back up.
  # See example-volsync.yaml for the template.
